import type {
  Position,
  Transaction,
  WatchlistItem,
  Watchlist,
  JournalEntry,
  MarketIndex,
  NewsItem,
  ChartDataPoint,
  AllocationSlice,
  InsightCard,
  PortfolioSummary,
  TopMover,
} from "./types";

// ─── Portfolio Positions ──────────────────────────────────────────────────────

export const mockPositions: Position[] = [
  {
    id: "pos-1",
    ticker: "AAPL",
    name: "Apple Inc.",
    assetClass: "stock",
    sector: "Technology",
    geography: "United States",
    exchange: "NASDAQ",
    currency: "USD",
    quantity: 250,
    avgCostBasis: 142.30,
    currentPrice: 189.45,
    previousClose: 187.20,
    marketValue: 47362.50,
    unrealisedPL: 11787.50,
    unrealisedPLPct: 33.12,
    dayChange: 562.50,
    dayChangePct: 1.20,
    weight: 12.4,
    dividendYield: 0.51,
    beta: 1.24,
    peRatio: 28.6,
    analystTarget: 205.00,
    logoUrl: "https://logo.clearbit.com/apple.com",
    addedDate: "2021-03-15",
    notes: "Core holding. Long-term conviction on services revenue flywheel and ecosystem lock-in.",
  },
  {
    id: "pos-2",
    ticker: "MSFT",
    name: "Microsoft Corporation",
    assetClass: "stock",
    sector: "Technology",
    geography: "United States",
    exchange: "NASDAQ",
    currency: "USD",
    quantity: 120,
    avgCostBasis: 265.80,
    currentPrice: 428.70,
    previousClose: 424.10,
    marketValue: 51444.00,
    unrealisedPL: 19548.00,
    unrealisedPLPct: 61.34,
    dayChange: 552.00,
    dayChangePct: 1.08,
    weight: 13.5,
    dividendYield: 0.72,
    beta: 0.89,
    peRatio: 35.2,
    analystTarget: 470.00,
    logoUrl: "https://logo.clearbit.com/microsoft.com",
    addedDate: "2020-11-08",
    notes: "Azure + Copilot AI integration makes this the clear enterprise AI infrastructure play.",
  },
  {
    id: "pos-3",
    ticker: "NVDA",
    name: "NVIDIA Corporation",
    assetClass: "stock",
    sector: "Technology",
    geography: "United States",
    exchange: "NASDAQ",
    currency: "USD",
    quantity: 180,
    avgCostBasis: 320.50,
    currentPrice: 875.20,
    previousClose: 865.40,
    marketValue: 157536.00,
    unrealisedPL: 99846.00,
    unrealisedPLPct: 173.12,
    dayChange: 1764.00,
    dayChangePct: 1.13,
    weight: 18.2,
    dividendYield: 0.03,
    beta: 1.72,
    peRatio: 68.4,
    analystTarget: 1000.00,
    logoUrl: "https://logo.clearbit.com/nvidia.com",
    addedDate: "2022-10-12",
    notes: "AI infrastructure supercycle. Data centre GPU monopoly for the foreseeable future.",
  },
  {
    id: "pos-4",
    ticker: "LLOY",
    name: "Lloyds Banking Group",
    assetClass: "stock",
    sector: "Financials",
    geography: "United Kingdom",
    exchange: "LSE",
    currency: "GBP",
    quantity: 45000,
    avgCostBasis: 0.428,
    currentPrice: 0.562,
    previousClose: 0.558,
    marketValue: 25290.00,
    unrealisedPL: 6030.00,
    unrealisedPLPct: 31.31,
    dayChange: 180.00,
    dayChangePct: 0.72,
    weight: 6.6,
    dividendYield: 5.4,
    beta: 1.05,
    peRatio: 7.2,
    analystTarget: 0.65,
    logoUrl: "https://logo.clearbit.com/lloydsbank.com",
    addedDate: "2023-01-20",
    notes: "High dividend yield. UK rate environment supportive. Cheap on P/B.",
  },
  {
    id: "pos-5",
    ticker: "VWRL",
    name: "Vanguard FTSE All-World ETF",
    assetClass: "etf",
    sector: "Technology",
    geography: "Global",
    exchange: "LSE",
    currency: "GBP",
    quantity: 380,
    avgCostBasis: 88.50,
    currentPrice: 108.40,
    previousClose: 107.60,
    marketValue: 41192.00,
    unrealisedPL: 7562.00,
    unrealisedPLPct: 22.50,
    dayChange: 304.00,
    dayChangePct: 0.74,
    weight: 10.8,
    dividendYield: 1.62,
    beta: 0.98,
    addedDate: "2020-06-01",
    notes: "Core passive allocation. Rebalances global equity exposure.",
  },
  {
    id: "pos-6",
    ticker: "SMT",
    name: "Scottish Mortgage Investment Trust",
    assetClass: "fund",
    sector: "Technology",
    geography: "Global",
    exchange: "LSE",
    currency: "GBP",
    quantity: 3200,
    avgCostBasis: 8.40,
    currentPrice: 9.15,
    previousClose: 9.08,
    marketValue: 29280.00,
    unrealisedPL: 2400.00,
    unrealisedPLPct: 8.93,
    dayChange: 224.00,
    dayChangePct: 0.77,
    weight: 7.7,
    beta: 1.45,
    addedDate: "2022-04-18",
    notes: "Baillie Gifford long-term growth mandate. Significant private company exposure.",
  },
  {
    id: "pos-7",
    ticker: "AMZN",
    name: "Amazon.com Inc.",
    assetClass: "stock",
    sector: "Consumer Discretionary",
    geography: "United States",
    exchange: "NASDAQ",
    currency: "USD",
    quantity: 95,
    avgCostBasis: 148.20,
    currentPrice: 192.50,
    previousClose: 189.80,
    marketValue: 18287.50,
    unrealisedPL: 4208.50,
    unrealisedPLPct: 29.88,
    dayChange: 256.50,
    dayChangePct: 1.42,
    weight: 4.8,
    beta: 1.31,
    peRatio: 42.1,
    analystTarget: 225.00,
    logoUrl: "https://logo.clearbit.com/amazon.com",
    addedDate: "2023-03-05",
    notes: "AWS operating leverage story. Retail margin expansion underappreciated.",
  },
  {
    id: "pos-8",
    ticker: "BP.",
    name: "BP p.l.c.",
    assetClass: "stock",
    sector: "Energy",
    geography: "United Kingdom",
    exchange: "LSE",
    currency: "GBP",
    quantity: 8500,
    avgCostBasis: 4.38,
    currentPrice: 4.72,
    previousClose: 4.76,
    marketValue: 40120.00,
    unrealisedPL: 2890.00,
    unrealisedPLPct: 7.76,
    dayChange: -340.00,
    dayChangePct: -0.84,
    weight: 10.5,
    dividendYield: 5.1,
    beta: 0.82,
    peRatio: 9.8,
    analystTarget: 5.50,
    logoUrl: "https://logo.clearbit.com/bp.com",
    addedDate: "2023-09-14",
  },
  {
    id: "pos-9",
    ticker: "HSBA",
    name: "HSBC Holdings plc",
    assetClass: "stock",
    sector: "Financials",
    geography: "United Kingdom",
    exchange: "LSE",
    currency: "GBP",
    quantity: 3800,
    avgCostBasis: 5.82,
    currentPrice: 6.94,
    previousClose: 6.88,
    marketValue: 26372.00,
    unrealisedPL: 4256.00,
    unrealisedPLPct: 19.24,
    dayChange: 228.00,
    dayChangePct: 0.87,
    weight: 6.9,
    dividendYield: 6.8,
    beta: 0.74,
    peRatio: 8.1,
    analystTarget: 8.00,
    logoUrl: "https://logo.clearbit.com/hsbc.com",
    addedDate: "2022-12-01",
    notes: "Asia exposure + high dividend. Beneficiary of EM growth.",
  },
  {
    id: "pos-10",
    ticker: "CASH",
    name: "Cash & Money Market",
    assetClass: "cash",
    sector: "Cash & Equivalents",
    geography: "United Kingdom",
    exchange: "OTHER",
    currency: "GBP",
    quantity: 1,
    avgCostBasis: 28500.00,
    currentPrice: 28500.00,
    previousClose: 28500.00,
    marketValue: 28500.00,
    unrealisedPL: 0,
    unrealisedPLPct: 0,
    dayChange: 0,
    dayChangePct: 0,
    weight: 7.5,
    dividendYield: 5.2,
    addedDate: "2024-01-01",
    notes: "Cash drag. Target to deploy into next dip.",
  },
];

// ─── Portfolio Summary ────────────────────────────────────────────────────────

export const mockPortfolioSummary: PortfolioSummary = {
  totalValue: 383384.00,
  totalCost: 268450.00,
  totalUnrealisedPL: 114934.00,
  totalUnrealisedPLPct: 42.81,
  dailyPL: 3731.00,
  dailyPLPct: 0.98,
  cashBalance: 28500.00,
  cashPct: 7.4,
  positions: mockPositions,
  currency: "GBP",
  lastUpdated: new Date().toISOString(),
};

// ─── Transactions ─────────────────────────────────────────────────────────────

export const mockTransactions: Transaction[] = [
  {
    id: "txn-1",
    positionId: "pos-3",
    ticker: "NVDA",
    name: "NVIDIA Corporation",
    type: "buy",
    quantity: 80,
    price: 298.40,
    total: 23872.00,
    currency: "USD",
    date: "2024-01-08",
    broker: "IG Index",
    notes: "Added on AI infrastructure thesis confirmation",
  },
  {
    id: "txn-2",
    positionId: "pos-1",
    ticker: "AAPL",
    name: "Apple Inc.",
    type: "buy",
    quantity: 50,
    price: 184.20,
    total: 9210.00,
    currency: "USD",
    date: "2024-01-22",
    broker: "IG Index",
  },
  {
    id: "txn-3",
    positionId: "pos-9",
    ticker: "HSBA",
    name: "HSBC Holdings plc",
    type: "dividend",
    quantity: 3800,
    price: 0.31,
    total: 1178.00,
    currency: "GBP",
    date: "2024-02-14",
    broker: "IG Index",
    notes: "Q4 2023 interim dividend",
  },
  {
    id: "txn-4",
    positionId: "pos-2",
    ticker: "MSFT",
    name: "Microsoft Corporation",
    type: "buy",
    quantity: 30,
    price: 404.80,
    total: 12144.00,
    currency: "USD",
    date: "2024-03-01",
    broker: "IG Index",
    notes: "Copilot monetisation beginning to show in results",
  },
  {
    id: "txn-5",
    positionId: "pos-8",
    ticker: "BP.",
    name: "BP p.l.c.",
    type: "buy",
    quantity: 2000,
    price: 4.85,
    total: 9700.00,
    currency: "GBP",
    date: "2024-04-10",
    broker: "IG Index",
    notes: "Added on weakness. Oil supply remains constrained.",
  },
  {
    id: "txn-6",
    positionId: "pos-7",
    ticker: "AMZN",
    name: "Amazon.com Inc.",
    type: "buy",
    quantity: 45,
    price: 178.90,
    total: 8050.50,
    currency: "USD",
    date: "2024-05-15",
    broker: "IG Index",
  },
  {
    id: "txn-7",
    positionId: "pos-4",
    ticker: "LLOY",
    name: "Lloyds Banking Group",
    type: "dividend",
    quantity: 45000,
    price: 0.0192,
    total: 864.00,
    currency: "GBP",
    date: "2024-05-28",
    broker: "IG Index",
    notes: "Final dividend FY2023",
  },
  {
    id: "txn-8",
    positionId: "pos-3",
    ticker: "NVDA",
    name: "NVIDIA Corporation",
    type: "buy",
    quantity: 100,
    price: 825.50,
    total: 82550.00,
    currency: "USD",
    date: "2024-06-05",
    broker: "IG Index",
    notes: "Post-split accumulation. Data centre demand trajectory intact.",
  },
];

// ─── Watchlists ───────────────────────────────────────────────────────────────

export const mockWatchlists: Watchlist[] = [
  {
    id: "wl-1",
    name: "High Conviction",
    createdAt: "2024-01-01",
    items: [
      {
        id: "w-1",
        ticker: "META",
        name: "Meta Platforms Inc.",
        assetClass: "stock",
        currentPrice: 524.80,
        dayChange: 8.40,
        dayChangePct: 1.63,
        targetPrice: 600.00,
        notes: "Advertising recovery + Reality Labs optionality. Zuckerberg's AI focus impressive.",
        addedDate: "2024-02-10",
        logoUrl: "https://logo.clearbit.com/meta.com",
      },
      {
        id: "w-2",
        ticker: "TSLA",
        name: "Tesla Inc.",
        assetClass: "stock",
        currentPrice: 182.50,
        dayChange: -4.20,
        dayChangePct: -2.25,
        targetPrice: 250.00,
        alertPrice: 165.00,
        notes: "FSD progress critical. Wait for clearer path to robotaxi profitability.",
        addedDate: "2024-03-05",
        logoUrl: "https://logo.clearbit.com/tesla.com",
      },
      {
        id: "w-3",
        ticker: "ASML",
        name: "ASML Holding N.V.",
        assetClass: "stock",
        currentPrice: 842.40,
        dayChange: 12.80,
        dayChangePct: 1.54,
        targetPrice: 950.00,
        notes: "EUV monopoly. Sole supplier of lithography equipment for advanced chips. Strong moat.",
        addedDate: "2024-01-15",
        logoUrl: "https://logo.clearbit.com/asml.com",
      },
    ],
  },
  {
    id: "wl-2",
    name: "UK Opportunities",
    createdAt: "2024-02-14",
    items: [
      {
        id: "w-4",
        ticker: "AZN",
        name: "AstraZeneca plc",
        assetClass: "stock",
        currentPrice: 11840.00,
        dayChange: 184.00,
        dayChangePct: 1.58,
        targetPrice: 13000.00,
        notes: "Pipeline strength exceptional. Oncology portfolio world-class.",
        addedDate: "2024-04-20",
        logoUrl: "https://logo.clearbit.com/astrazeneca.com",
      },
      {
        id: "w-5",
        ticker: "LGEN",
        name: "Legal & General Group",
        assetClass: "stock",
        currentPrice: 2.38,
        dayChange: 0.02,
        dayChangePct: 0.85,
        targetPrice: 2.80,
        alertPrice: 2.20,
        notes: "9%+ dividend yield hard to ignore. Institutional asset management scale.",
        addedDate: "2024-05-01",
      },
    ],
  },
  {
    id: "wl-3",
    name: "Income & Dividends",
    createdAt: "2024-03-01",
    items: [
      {
        id: "w-6",
        ticker: "NCYF",
        name: "CQS Natural Resources Growth & Income",
        assetClass: "fund",
        currentPrice: 0.298,
        dayChange: 0.001,
        dayChangePct: 0.34,
        notes: "Natural resources income exposure. 8% yield.",
        addedDate: "2024-05-10",
      },
    ],
  },
];

// ─── Journal Entries ──────────────────────────────────────────────────────────

export const mockJournalEntries: JournalEntry[] = [
  {
    id: "j-1",
    title: "AI Infrastructure: The New Commodity Supercycle",
    body: `The parallel to the 1990s internet infrastructure buildout is striking but imperfect. What's different this time: the hyperscalers are profitable from day one, and the CapEx is going to a handful of monopolistic suppliers — primarily NVIDIA.\n\nMy thesis: NVDA is not just a GPU company, it's becoming the platform layer for AI compute. CUDA moats are real and switching costs are enormous. The $80bn data centre revenue guide for FY25 continues to surprise to the upside.\n\nAdded to position on the June dip. Will hold through the inevitable volatility.`,
    tags: ["AI", "infrastructure", "conviction"],
    tickers: ["NVDA", "MSFT", "AMZN"],
    type: "thesis",
    date: "2024-06-10",
    mood: "bullish",
  },
  {
    id: "j-2",
    title: "UK Banking: Rate Cycle Inflection",
    body: `Base rate now likely to be cut 2-3 times by year end per BoE guidance. This creates a headwind for NIM but the stocks have already priced in worse. LLOY trading at 0.7x P/B — historically attractive entry.\n\nDividend yield at 5.4% provides a meaningful floor. The mortgage book re-pricing risk is manageable given the fixed-rate book duration. Motor finance remains the key tail risk to monitor closely.\n\nMaintaining position but not adding here.`,
    tags: ["UK", "banking", "rates", "income"],
    tickers: ["LLOY", "HSBA"],
    type: "thesis",
    date: "2024-05-22",
    mood: "neutral",
  },
  {
    id: "j-3",
    title: "Lesson: Don't Fight the Macro in 2022",
    body: `Looking back at 2022 — held growth positions through rising rates when all the macro signals were clear. The Fed communicated explicitly what they were going to do, and I stayed long high-multiple tech.\n\nLesson learned: when central banks are in a tightening cycle and explicit about it, rotate to value/income. The math on DCF models is unambiguous — duration extension is not your friend in rising rate environments.\n\nThis is now a permanent rule in my process.`,
    tags: ["lessons", "macro", "process"],
    type: "lesson",
    date: "2024-01-05",
    mood: "neutral",
  },
  {
    id: "j-4",
    title: "Market Observations — June 2024",
    body: `US equity markets remain resilient despite "higher for longer" rhetoric. The mag-7 concentration risk continues to grow — S&P 500 top 10 names now represent 36% of the index.\n\nThis creates both an opportunity and a risk: opportunity in overlooked small/mid-cap names with earnings recovery; risk if anything dents AI sentiment in the mega-caps.\n\nGlobal diversification via VWRL remains important here. Watching EM debt dynamics carefully.`,
    tags: ["markets", "macro", "june-2024"],
    type: "market",
    date: "2024-06-15",
    mood: "neutral",
  },
];

// ─── Market Indices ───────────────────────────────────────────────────────────

export const mockMarketIndices: MarketIndex[] = [
  { name: "FTSE 100", ticker: "UKX", value: 8242.80, change: 48.40, changePct: 0.59, currency: "GBP" },
  { name: "S&P 500", ticker: "SPX", value: 5482.30, change: 28.40, changePct: 0.52, currency: "USD" },
  { name: "NASDAQ 100", ticker: "NDX", value: 19876.40, change: 214.60, changePct: 1.09, currency: "USD" },
  { name: "DOW JONES", ticker: "INDU", value: 38740.20, change: -42.80, changePct: -0.11, currency: "USD" },
  { name: "DAX", ticker: "DAX", value: 18420.60, change: 112.40, changePct: 0.61, currency: "EUR" },
  { name: "NIKKEI 225", ticker: "NKY", value: 38942.10, change: 362.80, changePct: 0.94, currency: "USD" },
];

// ─── News Feed ────────────────────────────────────────────────────────────────

export const mockNews: NewsItem[] = [
  {
    id: "n-1",
    headline: "NVIDIA Surpasses $3 Trillion Market Cap on Continued AI Demand",
    source: "Financial Times",
    url: "#",
    publishedAt: "2024-06-19T09:30:00Z",
    tickers: ["NVDA"],
    sentiment: "positive",
    summary: "NVIDIA briefly overtook Microsoft as the world's most valuable company as data centre demand continues to exceed analyst expectations.",
  },
  {
    id: "n-2",
    headline: "Bank of England Signals Possible Rate Cut in August Meeting",
    source: "Bloomberg",
    url: "#",
    publishedAt: "2024-06-19T08:15:00Z",
    tickers: ["LLOY", "HSBA"],
    sentiment: "neutral",
    summary: "MPC members indicate growing comfort with inflation trajectory, raising probability of August cut to 65%.",
  },
  {
    id: "n-3",
    headline: "Microsoft Azure Growth Accelerates to 31% in Latest Quarter",
    source: "Reuters",
    url: "#",
    publishedAt: "2024-06-18T18:45:00Z",
    tickers: ["MSFT"],
    sentiment: "positive",
    summary: "Cloud division's AI-driven workloads driving above-consensus growth, Copilot monetisation beginning to appear in revenue.",
  },
  {
    id: "n-4",
    headline: "BP Weighs Further Divestments Amid Activist Pressure",
    source: "The Times",
    url: "#",
    publishedAt: "2024-06-18T14:20:00Z",
    tickers: ["BP."],
    sentiment: "neutral",
    summary: "Elliott Management reportedly building stake as BP considers strategic options to narrow discount to NAV.",
  },
  {
    id: "n-5",
    headline: "Apple Vision Pro Developer Adoption Exceeds Internal Targets",
    source: "WSJ",
    url: "#",
    publishedAt: "2024-06-18T11:00:00Z",
    tickers: ["AAPL"],
    sentiment: "positive",
    summary: "Spatial computing platform attracting enterprise developers faster than expected, with healthcare and aviation verticals leading adoption.",
  },
  {
    id: "n-6",
    headline: "FTSE 100 Rises as Inflation Data Encourages Rate Cut Bets",
    source: "Guardian",
    url: "#",
    publishedAt: "2024-06-17T09:00:00Z",
    tickers: [],
    sentiment: "positive",
    summary: "UK CPI falls to 2.0% target for first time since 2021, boosting rate-sensitive sectors across the London market.",
  },
];

// ─── Performance Chart Data ───────────────────────────────────────────────────

function generatePortfolioHistory(): ChartDataPoint[] {
  const data: ChartDataPoint[] = [];
  let value = 240000;
  let benchmark = 240000;
  const start = new Date("2023-01-02");

  for (let i = 0; i < 370; i++) {
    const d = new Date(start);
    d.setDate(d.getDate() + i);
    if (d.getDay() === 0 || d.getDay() === 6) continue;

    const drift = 0.00055;
    const vol = 0.012;
    const bmVol = 0.008;
    const shock = Math.random();
    const dayReturn = drift + vol * (Math.random() * 2 - 1) + (shock > 0.97 ? 0.04 : shock < 0.03 ? -0.04 : 0);
    const bmReturn = drift * 0.7 + bmVol * (Math.random() * 2 - 1);

    value = value * (1 + dayReturn);
    benchmark = benchmark * (1 + bmReturn);

    data.push({
      date: d.toISOString().split("T")[0],
      value: Math.round(value),
      benchmark: Math.round(benchmark),
    });
  }

  return data;
}

export const mockPerformanceHistory = generatePortfolioHistory();

// ─── Allocation Data ──────────────────────────────────────────────────────────

export const mockSectorAllocation: AllocationSlice[] = [
  { name: "Technology", value: 44.1, color: "#6366f1" },
  { name: "Financials", value: 13.5, color: "#8b5cf6" },
  { name: "Energy", value: 10.5, color: "#f59e0b" },
  { name: "Consumer Disc.", value: 4.8, color: "#06b6d4" },
  { name: "Global Equity", value: 10.8, color: "#10b981" },
  { name: "Cash", value: 7.5, color: "#44445a" },
  { name: "Other", value: 8.8, color: "#ec4899" },
];

export const mockGeographyAllocation: AllocationSlice[] = [
  { name: "United States", value: 48.9, color: "#6366f1" },
  { name: "United Kingdom", value: 31.5, color: "#8b5cf6" },
  { name: "Global", value: 10.8, color: "#06b6d4" },
  { name: "Cash", value: 7.5, color: "#44445a" },
  { name: "Other", value: 1.3, color: "#10b981" },
];

export const mockAssetClassAllocation: AllocationSlice[] = [
  { name: "Stocks", value: 73.9, color: "#6366f1" },
  { name: "ETFs", value: 10.8, color: "#8b5cf6" },
  { name: "Investment Trusts", value: 7.7, color: "#06b6d4" },
  { name: "Cash", value: 7.5, color: "#44445a" },
];

// ─── Insights ─────────────────────────────────────────────────────────────────

export const mockInsights: InsightCard[] = [
  {
    id: "ins-1",
    type: "warning",
    title: "Tech Concentration Risk",
    body: "Technology sector now represents 44% of your portfolio — significantly above your 35% target. Consider rebalancing into underweight sectors.",
    metric: "44.1%",
    change: "+9.1% vs target",
    date: "2024-06-19",
  },
  {
    id: "ins-2",
    type: "success",
    title: "NVDA: Best Performer This Year",
    body: "NVIDIA has returned +173% since your average cost basis of £320.50. Position now represents 18.2% of total portfolio.",
    metric: "+£99,846",
    ticker: "NVDA",
    change: "+173.1% since entry",
    date: "2024-06-19",
  },
  {
    id: "ins-3",
    type: "info",
    title: "Dividends Received: Q2 2024",
    body: "Total dividend income received this quarter: £2,042. HSBA and LLOY are your largest income contributors.",
    metric: "£2,042",
    change: "+18% vs Q2 2023",
    date: "2024-06-19",
  },
  {
    id: "ins-4",
    type: "opportunity",
    title: "Cash Allocation Below Target",
    body: "Cash balance of 7.5% is near the lower end of your target 8-12% range. Recent market strength may provide deployment opportunities.",
    metric: "£28,500",
    change: "7.5% of portfolio",
    date: "2024-06-19",
  },
  {
    id: "ins-5",
    type: "info",
    title: "Portfolio Beta: 1.18",
    body: "Your portfolio beta is above 1.0, indicating above-market sensitivity. In a down market, expect ~18% more drawdown than the index.",
    metric: "β 1.18",
    change: "+0.08 vs last month",
    date: "2024-06-19",
  },
  {
    id: "ins-6",
    type: "success",
    title: "YTD Outperformance vs FTSE 100",
    body: "Portfolio up 28.4% YTD vs FTSE 100 +8.2%. Primary driver: NVDA (+173%) and MSFT (+22%). Risk-adjusted return (Sharpe: 1.42) remains strong.",
    metric: "+20.2%",
    change: "vs benchmark YTD",
    date: "2024-06-19",
  },
];

// ─── Top Movers ───────────────────────────────────────────────────────────────

export const mockTopMovers: TopMover[] = [
  { ticker: "NVDA", name: "NVIDIA", change: 9.80, changePct: 1.13, logoUrl: "https://logo.clearbit.com/nvidia.com" },
  { ticker: "META", name: "Meta", change: 8.40, changePct: 1.63, logoUrl: "https://logo.clearbit.com/meta.com" },
  { ticker: "MSFT", name: "Microsoft", change: 4.60, changePct: 1.08, logoUrl: "https://logo.clearbit.com/microsoft.com" },
  { ticker: "AAPL", name: "Apple", change: 2.25, changePct: 1.20, logoUrl: "https://logo.clearbit.com/apple.com" },
  { ticker: "BP.", name: "BP", change: -0.04, changePct: -0.84 },
  { ticker: "TSLA", name: "Tesla", change: -4.20, changePct: -2.25, logoUrl: "https://logo.clearbit.com/tesla.com" },
];

// ─── Sparkline Generator ──────────────────────────────────────────────────────

export function generateSparkline(trend: "up" | "down" | "flat", points = 20): number[] {
  const result: number[] = [];
  let v = 100;
  const drift = trend === "up" ? 0.3 : trend === "down" ? -0.3 : 0;
  for (let i = 0; i < points; i++) {
    v += drift + (Math.random() * 4 - 2);
    result.push(parseFloat(v.toFixed(2)));
  }
  return result;
}
